services:
  # Standard gmag11 MT5 Wine container
  mt5-wine-standard:
    image: gmag11/metatrader5_vnc:latest
    container_name: mt5-wine-standard
    environment:
      - CUSTOM_USER=trader
      - PASSWORD=SecurePass123
    volumes:
      - ./config:/config
    ports:
      - "3001:3000"   # VNC
      - "8001:8001"   # RPyC
    restart: unless-stopped

  # Separate connector container
  mt5-connector:
    build:
      context: .
      dockerfile: Dockerfile.connector
    container_name: mt5-connector
    environment:
      - MT5_LOGIN=7920878
      - MT5_PASSWORD=Srm@2025
      - MT5_SERVER=Eightcap-Demo
      - REDIS_HOST=trading-redis
    depends_on:
      - mt5-wine-standard
      - trading-redis
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

  # Your existing Redis
  trading-redis:
    image: redis:7-alpine
    container_name: trading-redis
    ports:
      - "6382:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data:
  config:
