services:
  # Your existing MT5 container configuration
  mt5-real:
    image: gmag11/metatrader5_vnc:latest
    container_name: mt5-real
    ports:
      - "3000:3000"  # Web VNC access
      - "8001:8001"  # Python API access
    environment:
      - CUSTOM_USER=trader
      - PASSWORD=secure123
    volumes:
      - ./mt5-config:/config
    restart: unless-stopped
    networks:
      - trading-network

  # Redis Database
  redis:
    image: redis:7-alpine
    container_name: trading-redis
    ports:
      - "6382:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - trading-network
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # MT5 Data Connector (Fixed)
  mt5-connector:
    build:
      context: .
      dockerfile: Dockerfile.mt5-connector
    container_name: mt5-connector
    environment:
      - PYTHONUNBUFFERED=1
      - UPDATE_INTERVAL=300  # Fetch data every 5 minutes
    depends_on:
      redis:
        condition: service_healthy
      mt5-real:
        condition: service_started
    volumes:
      - ./logs:/app/logs
      - /var/run/docker.sock:/var/run/docker.sock  # Access to Docker
    restart: unless-stopped
    networks:
      - trading-network

  # Your Trading Backend
  trading-backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: trading-backend
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - FLASK_ENV=development
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ./trading_system:/app/trading_system
      - ./logs:/app/logs
    ports:
      - "8009:8009"
    restart: unless-stopped
    networks:
      - trading-network

volumes:
  redis_data:
    driver: local

networks:
  trading-network:
    driver: bridge
